version: '3'

name: exercism-bash

services:
  devcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../..:/workspaces:cached
      - dot_config:/root/.config
      - exercism:/root/exercism
    command: sleep infinity
    network_mode: host

volumes:
  dot_config:
  exercism:
